### ISSUE TITLE
graphql-request

### ISSUE THREAD

**Issue by diar-kourehpaz** [auth0-extensions/canirequire#298]
### Package info

Package Name: `graphql-request`

Package Version: `3.6.1`

NPM Url: https://www.npmjs.com/package/graphql-request

### Reason for Request

Currently the Auth0 registry has the 1.8.1 version which is 3 years old. It would be ideal to upgrade this package.

**Comment by seejee** [comment]
Hi @99diagha! Unfortunately, we weren't able to upgrade this package because version 3.6.1 [is not supported on Node 12](https://github.com/prisma-labs/graphql-request#node-version-support). We'll reevaluate this one Node 16+ is available for Rules. In the mean time, we have Node 16 support in Actions so this package should be usable there. Thank you!
